fragment UserJob on Job {
  id
  createdAt
  updatedAt
  position
  role
  description
  applyUrl
  remote
  status
  type
  tags {
    id
    name
  }
}

query User {
  user {
    id
    name
    email
    jobs {
      ...UserJob
    }
    company {
      id
      name
      description
      slug
      email
      website
      logoUrl
      twitter
    }
    likes {
      id
      createdAt
      position
      role
      company {
        id
        name
        slug
      }
      tags {
        id
        name
      }
    }
    alerts {
      id
      filter
    }
  }
}
