/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import type * as prisma from '.prisma/client'
import type { Context } from './../context'
import type { core } from 'nexus'
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void // "DateTime";
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CreateCheckoutSessionInput: {
    // input type
    name: string // String!
    price: number // Int!
  }
  CreateJobInput: {
    // input type
    applyUrl: string // String!
    description: string // String!
    position: string // String!
    remote: boolean // Boolean!
    role: NexusGenEnums['JobRole'] // JobRole!
    tags: string[] // [ID!]!
  }
  CreateTagInput: {
    // input type
    name: string // String!
  }
  GetCitiesInput: {
    // input type
    country: string // String!
    query: string // String!
  }
  GetJobsInput: {
    // input type
    query: NexusGenInputs['GetJobsInputQuery'] // GetJobsInputQuery!
  }
  GetJobsInputQuery: {
    // input type
    remote: boolean // Boolean!
    tags: string[] // [ID!]!
  }
  GetTagsInput: {
    // input type
    notIn: string[] // [String!]!
    query: string // String!
  }
  UpdateCompanyInput: {
    // input type
    email: string // String!
    id: string // ID!
    name: string // String!
    twitter: string // String!
    website: string // String!
  }
  UpdateJobInput: {
    // input type
    applyUrl: string // String!
    description: string // String!
    id: string // ID!
    position: string // String!
    remote: boolean // Boolean!
    role: NexusGenEnums['JobRole'] // JobRole!
    tags: string[] // [ID!]!
  }
  UpdateUserInput: {
    // input type
    name: string // String!
  }
}

export interface NexusGenEnums {
  JobRole: prisma.JobRole
  JobStatus: prisma.JobStatus
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: Date
}

export interface NexusGenObjects {
  CheckoutSessionResult: {
    // root type
    amount: number // Int!
    id: string // String!
  }
  City: {
    // root type
    label: string // ID!
    value: string // String!
  }
  Company: prisma.Company
  CreateBillingPortalSessionResult: {
    // root type
    url: string // String!
  }
  CreateCheckoutSessionResult: {
    // root type
    sessionUrl: string // String!
  }
  Job: prisma.Job
  Mutation: {}
  Query: {}
  SuccessResult: {
    // root type
    success: boolean // Boolean!
  }
  Tag: prisma.Tag
  User: prisma.User
}

export interface NexusGenInterfaces {}

export interface NexusGenUnions {}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes &
  NexusGenScalars &
  NexusGenEnums

export interface NexusGenFieldTypes {
  CheckoutSessionResult: {
    // field return type
    amount: number // Int!
    id: string // String!
  }
  City: {
    // field return type
    label: string // ID!
    value: string // String!
  }
  Company: {
    // field return type
    createdAt: NexusGenScalars['DateTime'] // DateTime!
    description: string // String!
    email: string // String!
    id: string // ID!
    jobs: NexusGenRootTypes['Job'][] // [Job!]!
    name: string // String!
    slug: string // String!
    twitter: string | null // String
    updatedAt: NexusGenScalars['DateTime'] // DateTime!
    viewCount: number // Int!
    website: string // String!
  }
  CreateBillingPortalSessionResult: {
    // field return type
    url: string // String!
  }
  CreateCheckoutSessionResult: {
    // field return type
    sessionUrl: string // String!
  }
  Job: {
    // field return type
    applyUrl: string // String!
    company: NexusGenRootTypes['Company'] // Company!
    createdAt: NexusGenScalars['DateTime'] // DateTime!
    description: string // String!
    id: string // ID!
    liked: boolean // Boolean!
    position: string // String!
    remote: boolean // Boolean!
    role: NexusGenEnums['JobRole'] // JobRole!
    status: NexusGenEnums['JobStatus'] // JobStatus!
    tags: NexusGenRootTypes['Tag'][] // [Tag!]!
    updatedAt: NexusGenScalars['DateTime'] // DateTime!
    viewCount: number // Int!
  }
  Mutation: {
    // field return type
    addLike: NexusGenRootTypes['Job'] // Job!
    createBillingPortalSession: NexusGenRootTypes['CreateBillingPortalSessionResult'] // CreateBillingPortalSessionResult!
    createCheckoutSession: NexusGenRootTypes['CreateCheckoutSessionResult'] // CreateCheckoutSessionResult!
    createJob: NexusGenRootTypes['Job'] // Job!
    createTag: NexusGenRootTypes['Tag'] // Tag!
    removeLike: NexusGenRootTypes['Job'] // Job!
    updateCompany: NexusGenRootTypes['Company'] // Company!
    updateJob: NexusGenRootTypes['Job'] // Job!
    updateUser: NexusGenRootTypes['User'] // User!
    viewCompany: NexusGenRootTypes['Company'] // Company!
    viewJob: NexusGenRootTypes['Job'] // Job!
  }
  Query: {
    // field return type
    checkoutSession: NexusGenRootTypes['CheckoutSessionResult'] // CheckoutSessionResult!
    cities: NexusGenRootTypes['City'][] // [City!]!
    companies: NexusGenRootTypes['Company'][] // [Company!]!
    company: NexusGenRootTypes['Company'] // Company!
    companyBySlug: NexusGenRootTypes['Company'] // Company!
    job: NexusGenRootTypes['Job'] // Job!
    jobs: NexusGenRootTypes['Job'][] // [Job!]!
    tags: NexusGenRootTypes['Tag'][] // [Tag!]!
    user: NexusGenRootTypes['User'] // User!
  }
  SuccessResult: {
    // field return type
    success: boolean // Boolean!
  }
  Tag: {
    // field return type
    count: number // Int!
    id: string // ID!
    name: string // String!
  }
  User: {
    // field return type
    company: NexusGenRootTypes['Company'] | null // Company
    email: string | null // String
    id: string // ID!
    jobs: NexusGenRootTypes['Job'][] // [Job!]!
    likes: NexusGenRootTypes['Job'][] // [Job!]!
    name: string | null // String
  }
}

export interface NexusGenFieldTypeNames {
  CheckoutSessionResult: {
    // field return type name
    amount: 'Int'
    id: 'String'
  }
  City: {
    // field return type name
    label: 'ID'
    value: 'String'
  }
  Company: {
    // field return type name
    createdAt: 'DateTime'
    description: 'String'
    email: 'String'
    id: 'ID'
    jobs: 'Job'
    name: 'String'
    slug: 'String'
    twitter: 'String'
    updatedAt: 'DateTime'
    viewCount: 'Int'
    website: 'String'
  }
  CreateBillingPortalSessionResult: {
    // field return type name
    url: 'String'
  }
  CreateCheckoutSessionResult: {
    // field return type name
    sessionUrl: 'String'
  }
  Job: {
    // field return type name
    applyUrl: 'String'
    company: 'Company'
    createdAt: 'DateTime'
    description: 'String'
    id: 'ID'
    liked: 'Boolean'
    position: 'String'
    remote: 'Boolean'
    role: 'JobRole'
    status: 'JobStatus'
    tags: 'Tag'
    updatedAt: 'DateTime'
    viewCount: 'Int'
  }
  Mutation: {
    // field return type name
    addLike: 'Job'
    createBillingPortalSession: 'CreateBillingPortalSessionResult'
    createCheckoutSession: 'CreateCheckoutSessionResult'
    createJob: 'Job'
    createTag: 'Tag'
    removeLike: 'Job'
    updateCompany: 'Company'
    updateJob: 'Job'
    updateUser: 'User'
    viewCompany: 'Company'
    viewJob: 'Job'
  }
  Query: {
    // field return type name
    checkoutSession: 'CheckoutSessionResult'
    cities: 'City'
    companies: 'Company'
    company: 'Company'
    companyBySlug: 'Company'
    job: 'Job'
    jobs: 'Job'
    tags: 'Tag'
    user: 'User'
  }
  SuccessResult: {
    // field return type name
    success: 'Boolean'
  }
  Tag: {
    // field return type name
    count: 'Int'
    id: 'ID'
    name: 'String'
  }
  User: {
    // field return type name
    company: 'Company'
    email: 'String'
    id: 'ID'
    jobs: 'Job'
    likes: 'Job'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addLike: {
      // args
      id: string // ID!
    }
    createCheckoutSession: {
      // args
      input: NexusGenInputs['CreateCheckoutSessionInput'] // CreateCheckoutSessionInput!
    }
    createJob: {
      // args
      input: NexusGenInputs['CreateJobInput'] // CreateJobInput!
    }
    createTag: {
      // args
      input: NexusGenInputs['CreateTagInput'] // CreateTagInput!
    }
    removeLike: {
      // args
      id: string // ID!
    }
    updateCompany: {
      // args
      input: NexusGenInputs['UpdateCompanyInput'] // UpdateCompanyInput!
    }
    updateJob: {
      // args
      input: NexusGenInputs['UpdateJobInput'] // UpdateJobInput!
    }
    updateUser: {
      // args
      input: NexusGenInputs['UpdateUserInput'] // UpdateUserInput!
    }
    viewCompany: {
      // args
      id: string // ID!
    }
    viewJob: {
      // args
      id: string // ID!
    }
  }
  Query: {
    checkoutSession: {
      // args
      id: string // ID!
    }
    cities: {
      // args
      input: NexusGenInputs['GetCitiesInput'] // GetCitiesInput!
    }
    company: {
      // args
      id: string // ID!
    }
    companyBySlug: {
      // args
      slug: string // String!
    }
    job: {
      // args
      id: string // ID!
    }
    jobs: {
      // args
      input: NexusGenInputs['GetJobsInput'] // GetJobsInput!
    }
    tags: {
      // args
      input: NexusGenInputs['GetTagsInput'] // GetTagsInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {}

export interface NexusGenTypeInterfaces {}

export type NexusGenObjectNames = keyof NexusGenObjects

export type NexusGenInputNames = keyof NexusGenInputs

export type NexusGenEnumNames = keyof NexusGenEnums

export type NexusGenInterfaceNames = never

export type NexusGenScalarNames = keyof NexusGenScalars

export type NexusGenUnionNames = never

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never

export type NexusGenAbstractsUsingStrategyResolveType = never

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context
  inputTypes: NexusGenInputs
  rootTypes: NexusGenRootTypes
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars
  argTypes: NexusGenArgTypes
  fieldTypes: NexusGenFieldTypes
  fieldTypeNames: NexusGenFieldTypeNames
  allTypes: NexusGenAllTypes
  typeInterfaces: NexusGenTypeInterfaces
  objectNames: NexusGenObjectNames
  inputNames: NexusGenInputNames
  enumNames: NexusGenEnumNames
  interfaceNames: NexusGenInterfaceNames
  scalarNames: NexusGenScalarNames
  unionNames: NexusGenUnionNames
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames']
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames']
  allNamedTypes:
    | NexusGenTypes['allInputTypes']
    | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames']
  abstractTypeMembers: NexusGenAbstractTypeMembers
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType
  features: NexusGenFeaturesConfig
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginInputFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginSchemaConfig {}
  interface NexusGenPluginArgConfig {}
}
