query Jobs($filter: JobsFilter!) {
  jobs(filter: $filter) {
    id
    createdAt
    position
    tags {
      id
      name
    }
    role
    liked
    company {
      id
      name
      slug
    }
  }
}
