query Job($id: ID!) {
  job(id: $id) {
    id
    position
    role
    description
    applyUrl
    viewCount
    liked
    tags {
      id
      name
    }
    company {
      id
      name
      slug
      email
      website
      twitter
    }
  }
}
